services:
  pangeeclusterdev:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}  # 例如: http://192.168.1.10:7890
        HTTPS_PROXY: ${HTTPS_PROXY}  # 例如: http://192.168.1.10:7890
        NO_PROXY: ${NO_PROXY}  # 例如: localhost,127.0.0.1,.local
    privileged: true
    restart: unless-stopped
    environment:
      PANGEE_CLUSTER_LOGRUS_LEVEL: trace
      PANGEE_CLUSTER_ADMIN_LOGRUS_LEVEL: trace
      PANGEE_CLUSTER_DEFAULT_ADMIN_PASSWORD: 2432612431302464617343536e4858706f567278764f532f5274752f755a526c72694f30306d73456657674c7a39644b712f43436c6d64544e506375
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/workspaces:cached
      - "/etc/resolv.conf:/etc/resolv.conf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.ssh:/root/.ssh"
    ports:
      - "3322:22"
